### ISSUE TITLE
Zeebe Operate unable to import data after upgrade 1.0.1->1.3.3

### ISSUE THREAD

**Issue by gschelter** [camunda/camunda-cloud-helm#153] opened 2022-02-03 17:14 UTC
We are using Zeebe with the elasticsearch exporter and the Operate dashboard. After upgrading from 1.0.1 to 1.3.3 operate does not show any processes from after the update and prints migrations errors.
I tried to start versions 1.1 and 1.2 for both the zeebe broker and operate dashboard to migrate the data, but it didn't help. It seems operate is unable to use any of the new data saved by the new broker version.
Zeebe or Elasticsearch do not show any errors and I found data in the index zeebe-record_process-instance_1.3.3_2022-02-03, so the data should be saved correctly in elasticsearch.
[operate-logs.csv](https://github.com/camunda-community-hub/camunda-cloud-helm/files/7996714/operate-logs.csv)

Zeebe 1.3.3
Operate 1.3.3
Elasticsearch v7.14.1

**Comment by gschelter** [comment] 2022-02-03 17:35
I don't know if this is related to the issue: The elasticsearch index "operate-flownode-instance-1.3.0_" does not have any data stored from after the update. The activity stops exactly at the time of the update.

**Comment by santanaluiz** [comment] 2022-02-03 20:51
One issue noted from the logs is that seems it was jumped from `1.0` and `1.3` without finishing the import.
```
 "2022-02-03T16:35:19.606Z","testing-zeebe-operate","error",,"Import is not possible for Zeebe version: 1.0"
```

User should finalize importing all the data from zeebe, then update version.
Operate supports only importing data from one of the previous versions, that means:
- In version `1.3`, Operate can import data from `1.3` and `1.2`

(same would be true from 1.1 to 1.3, for example)

So if we had pending data, from 1.0 some things will get "stucked". So if a process instance, for example was not imported because of the mentioned above, that means every incident, variables, etc are also not able to be imported

**Comment by gschelter** [comment] 2022-02-03 21:01
Can I fix this by letting Operate 1.1 migrate the data? Or is this impossible now that we already have 1.3 data in elasticsearch?

**Comment by santanaluiz** [comment] 2022-02-04 09:24
I will try to reproduce your scenario and see how it behaves.
The problem in running Operate 1.1 now is that we had some migrations in between. We need to double check how it behaves.

But if Operate 1.1 runs fine, then it would make sense to stop zeebe, run Operate 1.1 and wait for it to finish importing. Once done, Update to 1.3 again

(not tested scenario, so I can not guarantee)

**Comment by gschelter** [comment] 2022-02-09 09:19
@santanaluiz Any updates on this already?

**Comment by santanaluiz** [comment] 2022-02-09 12:05
Unfortunately, you can't run version 1.1. after running migrations to 1.3.
Would you have backup of prior to this upgrade?

**Comment by gschelter** [comment] 2022-02-09 13:26
Yes, but we are running the new version for a couple of weeks now already and would loose all data in between and would get out of sync with our other systems.
Currently the only option for us seems to be a full reset of Zeebe. Can you tell me if there will be an update to migrate our data that we could wait for? Otherwise we would probably start the reset soon.

**Comment by Zelldon** [comment] 2022-02-25 09:03
I will close this issue, since it is unrelated to the charts itself. Please post related issues (for operate or tasklist) in the [forum](https://forum.camunda.io/) or [slack](https://zeebe-slack-invite.herokuapp.com/) .

**Closed by Zelldon** 2022-02-25 09:03 UTC
